CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(128) NOT NULL,
    SURNAME VARCHAR(128) NOT NULL,
    BALANCE DECIMAL,
    PRIMARY KEY (ID)
);
CREATE TABLE IF NOT EXISTS ACCOUNT(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    CUSTOMER INTEGER NOT NULL,
    INITIAL_CREDIT DECIMAL,
    CREATION_DATE TIMESTAMP,
    PRIMARY KEY (ID),
    FOREIGN KEY(CUSTOMER) REFERENCES CUSTOMER(ID)
);
CREATE TABLE IF NOT EXISTS TRANSACTION(
    ID INTEGER NOT NULL AUTO_INCREMENT,
    TRANSACTION_DETAIL VARCHAR(128),
    TRANSACTION_AMOUNT DECIMAL,
    TRANSACTION_DATE TIMESTAMP,
    ACCOUNT INTEGER NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY(ACCOUNT) REFERENCES ACCOUNT(ID)
);